version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-1
    volumes:
      - kafka:/bitnami
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    ports:
      - 8080:8080
    restart: "always"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    depends_on:
      - kafka

  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    container_name: elastic-1
    volumes:
      - elastic:/bitnami
    ports:
      - 9200:9200

  kibana:
    image: 'bitnami/kibana:latest'
    container_name: kibana-1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elastic:
  kafka:
